name: 'Terraform'
on:
  push:
    branches:
    - main
  pull_request:
  
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
 
# Use the Bash shell regardless of whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          run: terraform init
    # Generates an execution plan for Terraform
        - name: Terraform Plan
          run: terraform plan -input=false
    # Apply Terraform changes
        - name: Terraform Apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false
          
  # tfsec is a static analysis security scanner for your Terraform code

  tfsec:
      name: tfsec sarif report
      runs-on: ubuntu-latest

      steps:
        - name: tfsec
          uses: tfsec/tfsec-sarif-action@v0.0.3
          with:
            working_directory: terraform/relevant
            sarif_file: tfsec.sarif         
            github_token: ${{ secrets.GITHUB_TOKEN }}
